/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.travel.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.travel.model.Trip;
import com.liferay.travel.model.TripModel;
import com.liferay.travel.model.TripSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Trip service. Represents a row in the &quot;FOO_Trip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TripModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TripImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TripImpl
 * @generated
 */
@JSON(strict = true)
public class TripModelImpl extends BaseModelImpl<Trip> implements TripModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trip model instance should use the <code>Trip</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Trip";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"tripId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"startingDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tripId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startingDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_Trip (uuid_ VARCHAR(75) null,tripId LONG not null primary key,name VARCHAR(75) null,startingDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_Trip";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trip.startingDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_Trip.startingDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long STARTINGDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Trip toModel(TripSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Trip model = new TripImpl();

		model.setUuid(soapModel.getUuid());
		model.setTripId(soapModel.getTripId());
		model.setName(soapModel.getName());
		model.setStartingDate(soapModel.getStartingDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Trip> toModels(TripSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Trip> models = new ArrayList<Trip>(soapModels.length);

		for (TripSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TripModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tripId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTripId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tripId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Trip.class;
	}

	@Override
	public String getModelClassName() {
		return Trip.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Trip)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Trip, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Trip, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Trip)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Trip, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Trip, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Trip>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Trip.class.getClassLoader(), Trip.class, ModelWrapper.class);

		try {
			Constructor<Trip> constructor =
				(Constructor<Trip>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Trip, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Trip, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Trip, Object>>();
		Map<String, BiConsumer<Trip, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Trip, ?>>();

		attributeGetterFunctions.put("uuid", Trip::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Trip, String>)Trip::setUuid);
		attributeGetterFunctions.put("tripId", Trip::getTripId);
		attributeSetterBiConsumers.put(
			"tripId", (BiConsumer<Trip, Long>)Trip::setTripId);
		attributeGetterFunctions.put("name", Trip::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Trip, String>)Trip::setName);
		attributeGetterFunctions.put("startingDate", Trip::getStartingDate);
		attributeSetterBiConsumers.put(
			"startingDate", (BiConsumer<Trip, Date>)Trip::setStartingDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTripId() {
		return _tripId;
	}

	@Override
	public void setTripId(long tripId) {
		_tripId = tripId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public Date getStartingDate() {
		return _startingDate;
	}

	@Override
	public void setStartingDate(Date startingDate) {
		_columnBitmask = -1L;

		_startingDate = startingDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Trip.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Trip toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Trip>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TripImpl tripImpl = new TripImpl();

		tripImpl.setUuid(getUuid());
		tripImpl.setTripId(getTripId());
		tripImpl.setName(getName());
		tripImpl.setStartingDate(getStartingDate());

		tripImpl.resetOriginalValues();

		return tripImpl;
	}

	@Override
	public int compareTo(Trip trip) {
		int value = 0;

		value = DateUtil.compareTo(getStartingDate(), trip.getStartingDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Trip)) {
			return false;
		}

		Trip trip = (Trip)object;

		long primaryKey = trip.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		TripModelImpl tripModelImpl = this;

		tripModelImpl._originalUuid = tripModelImpl._uuid;

		tripModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Trip> toCacheModel() {
		TripCacheModel tripCacheModel = new TripCacheModel();

		tripCacheModel.uuid = getUuid();

		String uuid = tripCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tripCacheModel.uuid = null;
		}

		tripCacheModel.tripId = getTripId();

		tripCacheModel.name = getName();

		String name = tripCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			tripCacheModel.name = null;
		}

		Date startingDate = getStartingDate();

		if (startingDate != null) {
			tripCacheModel.startingDate = startingDate.getTime();
		}
		else {
			tripCacheModel.startingDate = Long.MIN_VALUE;
		}

		return tripCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Trip)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Trip, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Trip, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Trip, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Trip)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Trip>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _tripId;
	private String _name;
	private Date _startingDate;
	private long _columnBitmask;
	private Trip _escapedModel;

}