apiDir: "../liferay-travel-rest-api/src/main/java"
apiPackagePath: "liferay.travel.rest"
application:
    baseURI: "/liferay-travel-rest"
    className: "LiferayTravelRESTApplication"
    name: "Liferay Travel REST API"
author: "Javier de Arcos"
